apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation-uid-allow
  labels:
    app: nginx-privilege-escalation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    runAsUser: 200
  containers:
  - name: nginx
    image: nginx
    securityContext:
      runAsUser: 0
